# TODO - Corregir la configuración e integración de Promtail

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
# Logs sistema
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
      
  # Logs app
- job_name: 'app-logs'
  static_configs:
    - targets:
        - localhost
      labels:
        job: app
        __path__: /app/logs/app.log