# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency: 
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  
  lint:
    name: golangci
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.x'

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
          version: v1.60

    - name: Run golangci-lint
      run: golangci-lint run --timeout 5m

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x', '1.22.x' ]

    needs: [lint]
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go ${{matrix.go-version}}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run Tests
      run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x', '1.22.x' ]

    needs: [lint, test]
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...
